### ISSUE TITLE
Problem with the Weathermap

### ISSUE THREAD

**Issue by Dobhars** [kozfelipe/centreon-weathermap#4] opened 2024-09-19 12:40 UTC
Hello i discovered your weathermap recently and i decided to install it to try, when i go to "Configuration -> Weathermap -> Maps" 
i don't have anything to create a map like you can see on the picture.
If you have any idea of what it could be, it would be cool.
Thanks

![image](https://github.com/user-attachments/assets/e3865c1b-84dd-40bd-8576-3ef7350c7bf3)

**Comment by kozfelipe** [comment] 2024-09-19 19:20
hello @Dobhars thanks for trying it out
I can see by the centreon's logo at your screenshot you are using a centreon's version above 22.10.x which might be the cause `modules/centreon-weathermap/maps.php` is not rendering properly.

It was designed for 22.04.x / 22.10.x but I intend to adapt it to current version as soon as I manage to upgrade my environment.

![image](https://github.com/user-attachments/assets/6b0124ea-ee43-46b3-b457-8e8e8cd9613b)

**Comment by Dobhars** [comment] 2024-09-20 07:45
Hello @kozfelipe, 
What’s strange is that on another of my servers centreon version 23.10.6, the map works perfectly, I do not understand why if it works on this one I can’t get it to work on my other centreon even if the module was made for earlier versions.

![image](https://github.com/user-attachments/assets/825691ab-3e01-4cb6-82da-32384ae66c7d)

![image](https://github.com/user-attachments/assets/a1f77e58-bfec-4a9d-8580-49d5bdc60703)

**Comment by kozfelipe** [comment] 2024-09-20 12:55
> Hello @kozfelipe, What’s strange is that on another of my servers centreon version 23.10.6, the map works perfectly, I do not understand why if it works on this one I can’t get it to work on my other centreon even if the module was made for earlier versions.

Are they both 23.10?

Is this page reporting javascript errors at your browser's console?
Also, make sure these pages are checked into Accessible Pages under ACL Menu Access

**Comment by Dobhars** [comment] 2024-09-20 13:28
It had the same version, i cloned the VM but since the map did not work I updated my second centreon to 24.04.6 but I think that was not necessarily a good idea and I did not backup the server before updating it so I can’t go back to an earlier version.

Do you have an idea of a release date for your module for versions 23+ or 24+?

**Comment by kozfelipe** [comment] 2024-09-20 13:48
My OS only supports up to 22.10.7
I am requesting my IT team to deploy a 24.04 VMWare image into dev environment to test this.

In the meanwhile you could check this:

> Is this page reporting javascript errors at your browser's console?
> Also, make sure these pages are checked into Accessible Pages under ACL Menu Access

**Comment by Dobhars** [comment] 2024-09-20 14:48
Here is a screenshot with the console, i have same errors on my centreon where the map is working so i don't think that is the problem.
And the pages are checked accessible in the ACL Menu Access.

![image](https://github.com/user-attachments/assets/aaaaf3c5-e29c-440f-80b7-1e57a1e9ceae)

**Comment by kozfelipe** [comment] 2024-09-20 15:04
those stylesheet errors are not really relevant.
If there are no errors on the frontend, we should check for backend errors.
could you check logs from php usually stored at:
`/var/log/apache2/error.log`

**Comment by Dobhars** [comment] 2024-09-20 16:40
I’m at school this week so I won’t have access to my company's centreon, I’ll send you that as soon as possible =)
Thank you again for taking the time to answer me.

**Comment by kozfelipe** [comment] 2024-09-24 13:57
So I have installed 24.04.6 and noticed 'php' tag is no longer supported in Smarty Compiler according to https://github.com/smarty-php/smarty/discussions/734 causing this error:

`PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "file:/usr/share/centreon/www/modules/centreon-weathermap/listMaps.ihtml"  on line 31 "{php}" unknown tag 'php' <-- \n  thrown in /usr/share/centreon/www/modules/centreon-weathermap/listMaps.ihtml on line 31' `

![image](https://github.com/user-attachments/assets/42133270-2edf-4bbb-990a-b5568c9c7055)

So apparently replacing 
```
{php}
     include('./include/common/pagination.php');
{/php}
```
for `{pagination}` on template files fix this issue

![image](https://github.com/user-attachments/assets/bbeed5a7-c374-43a2-a5de-8f9cec1e5641)

please apply these patches:

https://github.com/kozfelipe/centreon-weathermap/pull/5/commits/a9e120acd908e61c6e208b87794e8320293fa53e
https://github.com/kozfelipe/centreon-weathermap/pull/5/commits/a111afb0ef43f998c15495e5c849f134bc371141

or download the new branch files

**Comment by Dobhars** [comment] 2024-09-30 09:15
I downloaded the new branch files but still have the problem, so i checked the log and in the listMaps.ihtml you made a typo on line 73 you writed "ppagination", so I corrected it and it works.

Thank you again for taking the time to answer me and help me !

**Comment by kozfelipe** [comment] 2024-09-30 11:35
I am glad it worked

**Closed as completed by kozfelipe** 2024-09-30 11:35 UTC
